name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
      DEBUG_LEVEL: warning
      REFLEX_HOT_RELOAD_EXCLUDE_PATHS: data:docs:notebooks:temp:tests:twsapi

    strategy:
      matrix:
        python-version: ["3.10", "3.13"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Install TWS API (optional dependency)
      run: |
        pip install -U twsapi/IBJts/source/pythonclient || echo "TWS API installation failed, continuing without it"

    - name: Run tests with coverage
      run: |
        python -m pytest -vv tests/ \
          --cov=app \
          --cov-report=xml \
          --cov-report=html \
          --cov-report=term-missing \
          --cov-config=.coveragerc

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: always()
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Upload test results and coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.python-version }}
        path: |
          coverage.xml
          htmlcov/
          .pytest_cache/
          temp/
        retention-days: 7